# %% [markdown]
# # Delay cascade analysis: does a late arrival become a late departure?
#
# Consumes `analytics.turnarounds` (built by sql/06_turnaround.sql).
# Run cell by cell in VS Code (Ctrl+Enter on a `# %%` cell) or top to
# bottom as a script: `python python/02_delay_cascade.py`.
#
# Questions answered
# 1. How steeply does departure delay rise with arrival delay?
# 2. How many minutes of arrival delay pass through to the departure,
#    after controlling for scheduled ground time, carrier and hour?
# 3. How much scheduled ground buffer is enough to absorb a late arrival?
# 4. Which airlines propagate delay, and which generate it on the ground?
#
# Outputs: figures in reports/figures/, summary tables in data/processed/.

# %%
from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf

from db import FIG_DIR, PROCESSED_DIR, read_sql

FIG_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

plt.rcParams.update({"figure.dpi": 110, "axes.spines.top": False, "axes.spines.right": False})

# %% [markdown]
# ## 1. Load
# Only turns under 6 hours are relevant to a cascade: past that the
# departure is a separate rotation and any delay is its own story.

# %%
turns = read_sql(
    """
    SELECT arr_key, dep_key, registration, aircraft_type,
           airline_icao, airline_name, carrier_group,
           terminal_changed, arr_hour, arr_dow, turn_date,
           sched_ground_min, actual_ground_min, ground_variance,
           arr_delay_min, dep_delay_min, delay_recovered,
           arr_delayed_15, dep_delayed_15, is_propagated,
           turn_band, arr_delay_band, coverage_complete
    FROM analytics.turnarounds
    WHERE actual_ground_min < 360
    """
)
print(f"{len(turns):,} turns under 6 hours loaded")
print(turns[["sched_ground_min", "actual_ground_min", "arr_delay_min", "dep_delay_min"]].describe().round(1))

# %% [markdown]
# ## 2. The cascade curve
# Bin arrival delay in 10-minute steps and look at the share of following
# departures that were 15+ minutes late. Two carrier groups because the
# home carriers (Emirates, Flydubai) schedule far more ground time.

# %%
bins = list(range(-30, 130, 10))
turns["arr_bin"] = pd.cut(turns["arr_delay_min"].clip(-30, 129), bins=bins, right=False)

curve = (
    turns.groupby(["carrier_group", "arr_bin"], observed=True)
    .agg(turns=("dep_key", "size"), pct_dep_delayed=("dep_delayed_15", "mean"), avg_dep_delay=("dep_delay_min", "mean"))
    .reset_index()
)
curve["pct_dep_delayed"] = (100 * curve["pct_dep_delayed"]).round(1)
curve["bin_start"] = curve["arr_bin"].apply(lambda b: b.left)
curve.to_csv(PROCESSED_DIR / "cascade_curve.csv", index=False)

fig, ax = plt.subplots(figsize=(9, 5))
for grp, sub in curve.groupby("carrier_group"):
    sub = sub[sub["turns"] >= 200]
    ax.plot(sub["bin_start"], sub["pct_dep_delayed"], marker="o", label=grp)
ax.axhline(15, ls="--", lw=1, color="grey")
ax.set_xlabel("Arrival delay (minutes, 10-min bins)")
ax.set_ylabel("% of next departures delayed 15+ min")
ax.set_title("Departure delay rises steeply once an arrival is more than 15 minutes late")
ax.legend(frameon=False)
fig.tight_layout()
fig.savefig(FIG_DIR / "01_cascade_curve.png")
plt.show()

print(curve.pivot(index="bin_start", columns="carrier_group", values="pct_dep_delayed").to_string())

# %% [markdown]
# ## 3. Propagation coefficient (regression)
# Model departure delay as a function of *positive* arrival delay, scheduled
# ground time, carrier group and hour of day. The coefficient on
# `arr_late` is the number of minutes of departure delay generated by
# each minute of arrival delay after controls. Values near 1 mean delay
# passes straight through; values near 0 mean it is absorbed.
#
# OLS on clipped values keeps it interpretable for a portfolio write-up;
# a note in the README should say a quantile or robust model would be the
# next step because delays are heavy-tailed.

# %%
model_df = turns[(turns["dep_delay_min"].between(-60, 300)) & (turns["sched_ground_min"].between(20, 360))].copy()
model_df["arr_late"] = model_df["arr_delay_min"].clip(lower=0)
model_df["arr_early"] = (-model_df["arr_delay_min"]).clip(lower=0)
model_df["sched_ground_hr"] = model_df["sched_ground_min"] / 60
model_df["hour_band"] = pd.cut(
    model_df["arr_hour"], bins=[-1, 5, 11, 17, 23], labels=["Night 00-05", "Morning 06-11", "Afternoon 12-17", "Evening 18-23"]
)

ols = smf.ols(
    "dep_delay_min ~ arr_late + arr_early + sched_ground_hr + C(carrier_group) + C(hour_band) + C(terminal_changed)",
    data=model_df,
).fit(cov_type="HC1")
print(ols.summary().tables[1])
print(f"\nR-squared: {ols.rsquared:.3f}  |  n = {int(ols.nobs):,}")

coef = ols.params
print(
    f"\nEach minute of arrival delay adds {coef['arr_late']:.2f} min of departure delay, "
    f"and each extra scheduled hour on the ground removes {-coef['sched_ground_hr']:.1f} min."
)

# Propagation coefficient per carrier group (separate fits)
rows = []
for grp, sub in model_df.groupby("carrier_group"):
    m = smf.ols("dep_delay_min ~ arr_late + arr_early + sched_ground_hr + C(hour_band)", data=sub).fit()
    rows.append({"carrier_group": grp, "n": int(m.nobs), "passthrough_per_min": round(m.params["arr_late"], 3), "r2": round(m.rsquared, 3)})
passthrough = pd.DataFrame(rows)
print(passthrough.to_string(index=False))
passthrough.to_csv(PROCESSED_DIR / "passthrough_by_carrier_group.csv", index=False)

# %% [markdown]
# ## 4. How much buffer is enough?
# For arrivals that were late, split by scheduled ground time and see how
# much of the delay was recovered. This is the chart an operations
# manager would actually use.

# %%
late = turns[(turns["arr_delay_min"] > 15) & (turns["sched_ground_min"].between(30, 300))].copy()
late["sched_bin"] = pd.cut(late["sched_ground_min"], bins=[30, 60, 90, 120, 150, 180, 240, 300], right=False)

buffer_tbl = (
    late.groupby("sched_bin", observed=True)
    .agg(
        turns=("dep_key", "size"),
        avg_arr_delay=("arr_delay_min", "mean"),
        avg_dep_delay=("dep_delay_min", "mean"),
        pct_dep_delayed=("dep_delayed_15", "mean"),
        avg_recovered=("delay_recovered", "mean"),
    )
    .round(1)
)
buffer_tbl["pct_dep_delayed"] = (100 * buffer_tbl["pct_dep_delayed"]).round(1)
buffer_tbl["pct_recovered"] = (100 * buffer_tbl["avg_recovered"] / buffer_tbl["avg_arr_delay"]).round(1)
print(buffer_tbl.to_string())
buffer_tbl.reset_index().to_csv(PROCESSED_DIR / "buffer_vs_recovery.csv", index=False)

fig, ax = plt.subplots(figsize=(9, 5))
x = np.arange(len(buffer_tbl))
ax.bar(x, buffer_tbl["pct_dep_delayed"], color="#c0504d")
ax.set_xticks(x, [f"{int(i.left)}-{int(i.right)}" for i in buffer_tbl.index])
ax.set_xlabel("Scheduled ground time (minutes)")
ax.set_ylabel("% of departures delayed 15+ after a late (>15 min) arrival")
ax.set_title("More scheduled ground time steadily absorbs late arrivals")
for i, v in enumerate(buffer_tbl["pct_dep_delayed"]):
    ax.text(i, v + 1, f"{v:.0f}%", ha="center", fontsize=9)
fig.tight_layout()
fig.savefig(FIG_DIR / "02_buffer_vs_delay.png")
plt.show()

# %% [markdown]
# ## 5. Which airlines propagate delay, and which generate it?
# Split each airline's departure delay rate into two parts:
#  * baseline: departures after an ON-TIME arrival (delay created at DXB)
#  * propagated: departures after a LATE arrival (delay inherited)
# The gap between them is how well the airline recovers; the baseline is
# how much it creates on the ground. This separates the SpiceJet-vs-Saudia
# puzzle from the SQL validation.

# %%
quick = turns[turns["turn_band"].isin(["Quick (<90)", "Standard (90-180)"])].copy()
quick["arrival_state"] = np.where(quick["arr_delay_min"] > 15, "after_late_arrival", "after_ontime_arrival")

airline_tbl = (
    quick.groupby(["airline_name", "arrival_state"])
    .agg(turns=("dep_key", "size"), pct_dep_delayed=("dep_delayed_15", "mean"))
    .reset_index()
)
airline_tbl["pct_dep_delayed"] = (100 * airline_tbl["pct_dep_delayed"]).round(1)
wide = airline_tbl.pivot(index="airline_name", columns="arrival_state", values=["turns", "pct_dep_delayed"])
wide.columns = [f"{a}_{b}" for a, b in wide.columns]
wide = wide[(wide["turns_after_ontime_arrival"] >= 300) & (wide["turns_after_late_arrival"] >= 100)].copy()
wide["recovery_gap"] = (wide["pct_dep_delayed_after_late_arrival"] - wide["pct_dep_delayed_after_ontime_arrival"]).round(1)
wide = wide.sort_values("pct_dep_delayed_after_ontime_arrival", ascending=False)
print(wide.round(1).to_string())
wide.reset_index().to_csv(PROCESSED_DIR / "airline_baseline_vs_propagated.csv", index=False)

top = wide.head(15).sort_values("pct_dep_delayed_after_ontime_arrival")
fig, ax = plt.subplots(figsize=(9, 6))
y = np.arange(len(top))
ax.barh(y - 0.2, top["pct_dep_delayed_after_ontime_arrival"], height=0.4, label="After on-time arrival (created at DXB)", color="#4f81bd")
ax.barh(y + 0.2, top["pct_dep_delayed_after_late_arrival"], height=0.4, label="After late arrival (inherited)", color="#c0504d")
ax.set_yticks(y, top.index)
ax.set_xlabel("% of departures delayed 15+ min")
ax.set_title("Airlines with the highest ground-generated delay at DXB (quick and standard turns)")
ax.legend(frameon=False, loc="lower right")
fig.tight_layout()
fig.savefig(FIG_DIR / "03_airline_baseline_vs_propagated.png")
plt.show()

# %% [markdown]
# ## 6. Headline numbers for the README

# %%
ontime_arr = turns[turns["arr_delay_min"] <= 0]
late_arr = turns[turns["arr_delay_min"] > 30]
summary = {
    "turns_analysed": len(turns),
    "pct_dep_delayed_after_ontime_arrival": round(100 * ontime_arr["dep_delayed_15"].mean(), 1),
    "pct_dep_delayed_after_30plus_late_arrival": round(100 * late_arr["dep_delayed_15"].mean(), 1),
    "passthrough_minutes_per_minute": round(coef["arr_late"], 2),
    "minutes_absorbed_per_scheduled_hour": round(-coef["sched_ground_hr"], 1),
    "median_sched_ground_home_carrier": turns.loc[turns["carrier_group"] == "Home carrier", "sched_ground_min"].median(),
    "median_sched_ground_foreign_carrier": turns.loc[turns["carrier_group"] == "Foreign carrier", "sched_ground_min"].median(),
}
pd.Series(summary).to_csv(PROCESSED_DIR / "cascade_headline_numbers.csv", header=False)
for k, v in summary.items():
    print(f"{k:45s} {v}")
